### PR TITLE
Use unsafe calls to c

### PR DESCRIPTION
**Pull request by lpsmith**
There is substantial overhead involved with a safe call, that's easily much greater than the computation actually performed here.   And given that your helpers operate in a small constant time,  I don't see why you need a safe call.

### CODE REVIEW

**Comment by lpsmith** [comment]
Ok,  I did actually run a quick benchmark,  at it looks like unsafe calls are a least ~4x faster.    Here's the code:

```
import Criterion.Main
import Data.Word
import System.Endian
import qualified Data.Vector as V

main = defaultMain [ 
         bench "word64be" $ nf (V.map toBE64) (V.fromList [0..1023]) 
       , bench "word64le" $ nf (V.map toLE64) (V.fromList [0..1023]) 
       , bench "word32be" $ nf (V.map toBE32) (V.fromList [0..1023]) 
       , bench "word32le" $ nf (V.map toLE32) (V.fromList [0..1023]) 
       ]
```

With safe c calls:  

```
warming up
estimating clock resolution...
mean is 1.403279 us (640001 iterations)
found 3218 outliers among 639999 samples (0.5%)
  2929 (0.5%) high severe
estimating cost of a clock call...
mean is 34.46845 ns (13 iterations)

benchmarking word64be
mean: 61.19371 us, lb 61.11337 us, ub 61.30162 us, ci 0.950
std dev: 472.4794 ns, lb 380.1484 ns, ub 602.7302 ns, ci 0.950

benchmarking word64le
mean: 5.710830 us, lb 5.701874 us, ub 5.721559 us, ci 0.950
std dev: 49.86262 ns, lb 42.91008 ns, ub 60.19384 ns, ci 0.950

benchmarking word32be
mean: 60.68821 us, lb 60.60824 us, ub 60.78288 us, ci 0.950
std dev: 444.2457 ns, lb 385.0484 ns, ub 522.4285 ns, ci 0.950

benchmarking word32le
mean: 5.546265 us, lb 5.539084 us, ub 5.554903 us, ci 0.950
std dev: 40.32265 ns, lb 34.55300 ns, ub 48.54179 ns, ci 0.950
```

With unsafe C calls:

```
warming up
estimating clock resolution...
mean is 1.279086 us (640001 iterations)
found 2970 outliers among 639999 samples (0.5%)
  2736 (0.4%) high severe
estimating cost of a clock call...
mean is 34.45757 ns (12 iterations)

benchmarking word64be
mean: 16.85516 us, lb 16.82442 us, ub 16.89105 us, ci 0.950
std dev: 170.0308 ns, lb 150.1891 ns, ub 198.8732 ns, ci 0.950

benchmarking word64le
mean: 5.547027 us, lb 5.539677 us, ub 5.556200 us, ci 0.950
std dev: 41.99154 ns, lb 35.39848 ns, ub 52.29520 ns, ci 0.950

benchmarking word32be
mean: 16.51057 us, lb 16.48603 us, ub 16.53994 us, ci 0.950
std dev: 137.4619 ns, lb 115.6749 ns, ub 170.7115 ns, ci 0.950

benchmarking word32le
mean: 5.542775 us, lb 5.534050 us, ub 5.553165 us, ci 0.950
std dev: 48.75776 ns, lb 41.87533 ns, ub 58.27036 ns, ci 0.950
```

**Comment by vincenthz** [comment]
Thanks for the thorough benchmarks. you're absolutely right about this, no need for safe calls here.

Also in ghc 7.8 it's going to be replaced by much faster code with the work i've did around fast byteSwap directly in ghc http://ghc.haskell.org/trac/ghc/ticket/7902

**Comment by lpsmith** [comment]
That's good news.  I'm sure that given how little is actually going on here,  the overhead of even an unsafe C call is still much greater than the computation itself.  ;-)

**Comment by vincenthz** [comment]
yeah, i would think so too.

**Pull request merged**
